<?php

namespace ReportWriter\Report\Renderer;

use ReportWriter\Report\AbstractReport;

class HtmlTableRenderer implements RendererInterface
{
    private string $output = '';

    private array $columnKeys = [];

    private bool $tableOpened = false;

    private bool $theadRendered = false;

    private bool $tbodyOpened = false;

    private int $columnCount = 0;

    private array $columnOrder = [];

    private ?AbstractReport $report = null;

    private array $columnLabels = []; // optional, if you use it

    public function setReport(AbstractReport $report): self
    {
        $this->report = $report;

        return $this;
    }

    public function renderBand(string $type, ?int $level, $context): string
    {
        switch ($type) {
            case 'reportHeader':
                $this->renderReportHeader($context);
                break;

            case 'groupHeader':
                $this->renderGroupHeader($level ?? 0, $context);
                break;

            case 'detail':
                $this->renderDetail($context);
                break;

            case 'groupFooter':
                $this->renderGroupFooter($level ?? 0, $context);
                break;

            case 'summary':
                $this->renderSummary($context);
                break;

            case 'reportFooter':
                $this->renderReportFooter($context);
                break;
        }

        // We don't return per-band HTML anymore — it's all accumulated
        return '';
    }

    public function getOutput(): string
    {
        if ($this->tbodyOpened) {
            $this->output .= "</tbody>\n";
        }
        if ($this->tableOpened) {
            $this->output .= "</table>\n";
        }

        $this->output .= "<p>Report generated by ReportWriter</p>\n";

        return $this->output;
    }

    private function openTableIfNeeded(): void
    {
        if (!$this->tableOpened) {
            $this->output .= "<table class=\"report-table\">\n";
            $this->tableOpened = true;
        }
    }

    private function renderReportHeader(array $context): void
    {
        // Example: title, date, etc. Outside or above table
        $this->output .= "<h1>Report Title</h1>\n";
        $this->output .= "<p>Generated on: " . date('Y-m-d H:i') . "</p>\n";

        // Start the table after header
        $this->openTableIfNeeded();
        // We'll let groupHeader render <thead> if grouped
    }

    private function renderGroupHeader(int $level, array $context): void
    {
        $this->openTableIfNeeded();

        // Close previous group's tbody if open
        if ($this->tbodyOpened) {
            $this->output .= "</tbody>\n";
            $this->tbodyOpened = false;
        }

        // Render <thead> only once (level 0)
        if ($level === 0 && !$this->theadRendered) {
            if ($this->report && $this->report->hasConfiguredColumns()) {
                $this->columnOrder = $this->report->getColumnOrder();
                $this->columnCount = count($this->columnOrder);

                $this->output .= "<thead>\n  <tr>\n";
                foreach ($this->columnOrder as $field) {
                    $label = $this->report->getColumnLabel($field);
                    $this->output .= "    <th>" . htmlspecialchars($label) . "</th>\n";
                }
                $this->output .= "  </tr>\n</thead>\n";
            } else {
                // Fallback: auto-detect from first record
                $sampleRecord = $context['firstRecord'] ?? null;
                if ($sampleRecord) {
                    $this->columnKeys = array_keys($sampleRecord);
                    $this->columnKeys = array_filter($this->columnKeys, fn($k) => $k !== 'id');
                    $this->columnCount = count($this->columnKeys);

                    $this->output .= "<thead>\n  <tr>\n";
                    foreach ($this->columnKeys as $key) {
                        $this->output .= "    <th>" . htmlspecialchars(ucfirst($key)) . "</th>\n";
                    }
                    $this->output .= "  </tr>\n</thead>\n";
                }
            }

            $this->theadRendered = true;
        }

        // === START NEW TBODY AND ADD GROUP HEADER INSIDE IT ===
        $this->output .= "<tbody>\n";
        $this->tbodyOpened = true;

        $groupValue = htmlspecialchars($context['firstRecord']['category'] ?? 'Unknown Group');

        $this->output .= "  <tr class=\"group-header\">\n";
        $this->output .= "    <td colspan=\"{$this->columnCount}\"><strong>Group: {$groupValue}</strong></td>\n";
        $this->output .= "  </tr>\n";
        // === END ===
    }

    private function renderDetail(array $context): void
    {
        $this->openTableIfNeeded();

        if (!$this->tbodyOpened) {
            $this->output .= "<tbody>\n";
            $this->tbodyOpened = true;
        }

        $record = $context;

        $this->output .= "  <tr>\n";

        if ($this->report && $this->report->hasConfiguredColumns()) {
            foreach ($this->report->getColumnOrder() as $field) {
                $value = $record[$field] ?? '';
                $this->output .= "    <td>" . htmlspecialchars($value) . "</td>\n";
            }
        } else {
            // Fallback
            foreach ($record as $key => $value) {
                if ($key === 'id') continue;
                $this->output .= "    <td>" . htmlspecialchars($value) . "</td>\n";
            }
        }

        $this->output .= "  </tr>\n";
    }

    private function renderGroupFooter(int $level, array $context): void
    {
        $sum = $context['sumAmount'] ?? 0;

        $this->output .= "<tr class=\"group-footer\">\n";
        $this->output .= "<td colspan=\"" . ($this->columnCount - 1) . "\"><strong>Total for group</strong></td>\n";
        $this->output .= "<td><strong>" . htmlspecialchars($sum) . "</strong></td>\n";
        $this->output .= "</tr>\n";

        // Close tbody after footer
        if ($this->tbodyOpened) {
            $this->output .= "</tbody>\n";
            $this->tbodyOpened = false;
        }
    }

    private function renderSummary(array $context): void
    {
        if ($this->columnCount === 0) {
            return;
        }

        $grandTotal = $context['sumAmount'] ?? 'N/A';

        $this->output .= "<tfoot>\n";
        $this->output .= "<tr class=\"summary\">\n";
        $this->output .= "<td colspan=\"{$this->columnCount}\">";
        $this->output .= "<strong>Grand Total: " . htmlspecialchars($grandTotal) . "</strong>";
        $this->output .= "</td>\n";
        $this->output .= "</tr>\n";
        $this->output .= "</tfoot>\n";
    }

    private function renderReportFooter(array $context): void
    {
        // Page numbers, signatures, etc.
        // $this->output .= "<p>Report generated by ReportWriter</p>\n";
    }
}
