<?php

namespace ReportWriter\Report\Renderer;

use ReportWriter\Report\AbstractReport;

class HtmlTableRenderer extends AbstractRenderer
{
    private array $columnKeys = [];
    private bool $tableOpened = false;
    private bool $theadRendered = false;
    private bool $tbodyOpened = false;
    private int $columnCount = 0;
    private array $columnOrder = [];
    private ?AbstractReport $report = null;

    public function setReport(AbstractReport $report): self
    {
        $this->report = $report;

        return $this;
    }

    public function renderBand(string $type, ?int $level, $context): string
    {
        switch ($type) {
            case 'reportHeader':   $this->renderReportHeader($context);   break;
            case 'groupHeader':    $this->renderGroupHeader($level ?? 0, $context); break;
            case 'detail':         $this->renderDetail($context);         break;
            case 'groupFooter':    $this->renderGroupFooter($level ?? 0, $context); break;
            case 'summary':        $this->renderSummary($context);        break;
            case 'reportFooter':   $this->renderReportFooter($context);   break;
        }

        return '';
    }

    public function getOutput(): string
    {
        if ($this->tbodyOpened) {
            $this->appendLine('</tbody>');
        }
        if ($this->tableOpened) {
            $this->appendLine('</table>');
        }

        $this->appendLine('<p>Report generated by ReportWriter</p>');

        return parent::getOutput();
    }

    private function openTableIfNeeded(): void
    {
        if (!$this->tableOpened) {
            $this->appendLine('<table class="report-table">');
            $this->tableOpened = true;
        }
    }

    private function renderReportHeader(array $context): void
    {
        $this->appendLine('<h1>Report Title</h1>');
        $this->appendLine('<p>Generated on: ' . date('Y-m-d H:i') . '</p>');
        $this->openTableIfNeeded();
        // We'll let groupHeader render <thead> if grouped
    }

    private function renderGroupHeader(int $level, array $context): void
    {
        $this->openTableIfNeeded();

        if ($this->tbodyOpened) {
            $this->appendLine('</tbody>');
            $this->tbodyOpened = false;
        }

        $this->ensureColumnsConfigured($context);

        // Render <thead> only once
        if (!$this->theadRendered) {
            $this->appendLine('<thead>');
            $this->appendLine('  <tr>', 1);

            if ($this->report && $this->report->hasConfiguredColumns()) {
                foreach ($this->columnOrder as $field) {
                    $label = $this->report->getColumnLabel($field);
                    $this->appendLine('    <th>' . $this->escape($label) . '</th>', 2);
                }
            } else {
                foreach ($this->columnKeys as $key) {
                    $this->appendLine('    <th>' . $this->escape(ucfirst($key)) . '</th>', 2);
                }
            }

            $this->appendLine('  </tr>', 1);
            $this->appendLine('</thead>');
            $this->theadRendered = true;
        }

        // Now proceed with group header row...
        $this->appendLine('<tbody>');
        $this->tbodyOpened = true;

        $groupValue = $this->escape((string)($context['groupValue'] ?? 'Unknown Group'));

        $this->appendLine("  <tr class=\"group-header\">");
        $this->appendLine("    <td colspan=\"{$this->columnCount}\"><strong>Group: {$groupValue}</strong></td>");
        $this->appendLine("  </tr>");
    }

    private function renderDetail(array $context): void
    {
        $this->openTableIfNeeded();

        if (!$this->tbodyOpened) {
            $this->appendLine('<tbody>');
            $this->tbodyOpened = true;
        }

        $record = $context;

        $this->appendLine('<tr class="detail">', 1);

        if ($this->report && $this->report->hasConfiguredColumns()) {
            foreach ($this->report->getColumnOrder() as $field) {
                $rawValue = $record[$field] ?? '';
                $format = $this->report->getColumnFormat($field);
                $displayValue = $this->formatValue($rawValue, $format);

                $this->appendLine('    <td>' . $this->escape($displayValue) . '</td>', 2);
            }
        } else {
            // Fallback auto-detect
            foreach ($record as $key => $value) {
                if ($key === 'id') continue;
                $this->appendLine("    <td>" . htmlspecialchars($value) . "</td>", 2);
            }
        }

        $this->appendLine('</tr>', 1);
    }

    private function renderGroupFooter(int $level, array $context): void
    {
        $sum = $context['sumAmount'] ?? 0;

        $this->appendLine('<tr class="group-footer">');
        $this->appendLine("<td colspan=\"" . ($this->columnCount - 1) . "\"><strong>Total for group</strong></td>");
        $this->appendLine("<td><strong>" . htmlspecialchars($sum) . "</strong></td>");
        $this->appendLine('</tr>');

        // Close tbody after footer
        if ($this->tbodyOpened) {
            $this->appendLine('</tbody>');
            $this->tbodyOpened = false;
        }
    }

    private function renderSummary(array $context): void
    {
        if ($this->columnCount === 0) {
            return;
        }

        $grandTotal = $context['sumAmount'] ?? 'N/A';

        $this->appendLine('<tfoot>');
        $this->appendLine('<tr class=\"summary\">');
        $this->appendLine('<td colspan="{$this->columnCount}">');
        $this->appendLine("<strong>Grand Total: " . htmlspecialchars($grandTotal) . "</strong>");
        $this->appendLine('</td>');
        $this->appendLine('</tr>');
        $this->appendLine('</tfoot>');
    }

    private function renderReportFooter(array $context): void
    {
        // Page numbers, signatures, etc.
        // No output for HTML, rendered above. Fall thorough...
    }

    private function ensureColumnsConfigured(array $context): void
    {
        if ($this->columnCount > 0) {
            return; // already done
        }

        if ($this->report && $this->report->hasConfiguredColumns()) {
            $this->columnOrder = $this->report->getColumnOrder();
            $this->columnCount = count($this->columnOrder);
        } elseif (!empty($context['firstRecord'])) {
            // Fallback: auto-detect
            $record = $context['firstRecord'];
            $this->columnKeys = array_keys($record);
            $this->columnKeys = array_filter($this->columnKeys, fn($k) => $k !== 'id');
            $this->columnCount = count($this->columnKeys);
        }
    }
}
