<?php

declare(strict_types=1);

namespace ReportWriter\Tests\Unit\Report;

use PHPUnit\Framework\TestCase;
use ReportWriter\Report\Builder\GroupBuilder;
use ReportWriter\Report\Data\ArrayDataProvider;
use ReportWriter\Report\HtmlReport;
use ReportWriter\Report\Renderer\HtmlTableRenderer;

class HtmlReportWithTableRendererTest extends TestCase
{
    private const SAMPLE_DATA = [
        ['id' => 1, 'category' => 'A', 'amount' => 100, 'product' => 'Widget X'],
        ['id' => 2, 'category' => 'A', 'amount' => 200, 'product' => 'Widget Y'],
        ['id' => 3, 'category' => 'B', 'amount' => 300, 'product' => 'Gadget Z'],
    ];

    public function test_renders_full_html_table_with_correct_structure_and_aggregates(): void
    {

        // Setup data provider (we'll create a simple ArrayDataProvider)
        $dataProvider = new ArrayDataProvider(self::SAMPLE_DATA);

        // Create a renderer and report
        $renderer = new HtmlTableRenderer();
        $report = new HtmlReport($renderer);

        // Configure grouping and aggregates
        $groupBuilder = (new GroupBuilder('category'))
            ->sum('amount', 'sumAmount')
            ->count('amount', 'itemCount'); // should be same as recordCount

        $report
            ->setDataProvider($dataProvider)
            ->setGroups([$groupBuilder])
            ->setColumns([
                'product'  => 'Product',      // change order!
                'amount'   => 'Amount ($)',
                'category' => 'Category',
            ]);

        $html = $report->render();

        echo "\n--- GENERATED HTML ---\n";
        echo $html;
        echo "\n--- END HTML ---\n\n";

        // Check header order and labels
        $this->assertStringContainsString('<th>Product</th>', $html);
        $this->assertStringContainsString('<th>Amount ($)</th>', $html);
        $this->assertStringContainsString('<th>Category</th>', $html);

        // Check that Product appears before Amount before Category in thead
        $this->assertMatchesRegularExpression('/Product.*Amount \(\$\).*Category/s', $html);

        // Check a detail row has values in new order
        $this->assertMatchesRegularExpression('/Widget X.*100.*A/s', $html);

        // Assertions — check overall structure
        $this->assertStringContainsString('<table class="report-table">', $html);
        $this->assertStringContainsString('</table>', $html);

        $this->assertStringContainsString('<thead>', $html);
        $this->assertStringContainsString('<tbody>', $html);
        // We expect two <tbody> sections (one per group)
        $this->assertEquals(2, substr_count($html, '<tbody>'), 'Expected one tbody per group');

        // Check column headers (should auto-detect from first record)
        $this->assertStringContainsString('<th>Product</th>', $html);
        $this->assertStringContainsString('<th>Amount ($)</th>', $html);
        $this->assertStringContainsString('<th>Category</th>', $html);

        // Ensure headers appear in the correct configured order
        $this->assertMatchesRegularExpression(
            '/<th>Product<\/th>.*<th>Amount \(\$\)<\/th>.*<th>Category<\/th>/s',
            $html,
            'Headers should appear in the configured order: Product, Amount ($), Category'
        );

        $this->assertMatchesRegularExpression(
            '/Widget X.*100.*A/s',
            $html,
            'Detail row should show values in configured order: Product, Amount, Category'
        );
        $this->assertMatchesRegularExpression(
            '/Widget Y.*200.*A/s',
            $html
        );
        $this->assertMatchesRegularExpression(
            '/Gadget Z.*300.*B/s',
            $html
        );

        // Optional: confirm old label is gone
        $this->assertStringNotContainsString('<th>Amount</th>', $html);

        // Check group footers with aggregates
        // Group A: sum = 300, count = 2
        $this->assertStringContainsString('300', $html); // sumAmount
        $this->assertStringContainsString('Total for group', $html);

        // We can be more precise by checking context around the number
        $this->assertMatchesRegularExpression(
            '/Group: A.*?300/s',
            $html,
            'Group A should show sum of 300'
        );

        $this->assertMatchesRegularExpression(
            '/Group: B.*?300/s',
            $html,
            'Group B should show sum of 300'
        );

        // Check report header and footer
        $this->assertStringContainsString('<h1>Report Title</h1>', $html);
        $this->assertStringContainsString('Report generated by ReportWriter', $html);
    }
}